apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-server
  namespace: redis-server
  labels:
    app:  redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  redis-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  redis-server
        image:  redis:8.4.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-server
              key: ALLOW_EMPTY_PASSWORD
        ports:
        - containerPort:  6379
          name:  redis-server
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always 