apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robots-output
  namespace: robots
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
