apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jar-storage
  namespace: java-work-loader
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jar-storage
  resources:
    requests:
      storage: 1Gi