apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-orchestrator-
  namespace: job-orchestrator
  labels:
    app: job-orchestrator
    type: template
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: job-orchestrator
      labels:
        app: job-orchestrator
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-orchestrator
        image: rpa_kind_playwright/job-orchestrator:1.0
        command: ["python3"]
        args:
          - "/data/job-orchestrator/orchestrator.py"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: job-orchestrator-volume
          mountPath: /data/job-orchestrator/
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: job-orchestrator-volume
        persistentVolumeClaim:
            claimName: job-orchestrator-storage
