apiVersion: batch/v1
kind: Job
metadata:
  name: job-orchestrator
  namespace: job-orchestrator
  labels:
    app: job-orchestrator
spec:
  template:
    metadata:
      name: job-orchestrator
      labels:
        app: job-orchestrator
    spec:
      containers:
      - name: job-orchestrator
        image: python:3.7.6-alpine3.10
        command: ['sh', '-c', 'python3 orchestrator.py']
        env:
        - name: ENV_NAME
          value: ENV_VALUE
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
