apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-orchestrator-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/job-orchestrator